name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create zip file
        run: |
          cd custom_components
          zip -r tibber_data.zip tibber_data/
          mv tibber_data.zip ..

      - name: Upload zip file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tibber_data.zip
          asset_name: tibber_data.zip
          tag: ${{ github.ref }}
          overwrite: true